bundler_args: --without development
language: ruby
rvm:
  - 2.3.5
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.5.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.5.deb && true
  - 'printf "script:\n  inline: true\n  stored: true\n" | sudo tee --append /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch start
