version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.5
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
        environment:
          xpack.security.enabled: false
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
           key: bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle
      - run:
          name: Waiting for Elasticsearch
          command: dockerize --wait http://localhost:9200 -timeout 1m
      - run: bundle exec rspec spec
