version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.5
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
        environment:
          xpack.security.enabled: false
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
           key: bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Waiting for Elasticsearch
          command: dockerize --wait http://localhost:9200 -timeout 1m
      - run:
          name: RSpec
          environment:
            CC_TEST_REPORTER_ID: 23fafa5236bdcd23ae061f341aa8196519c3a2b9ca894f8c92dfedf03ee23511
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec spec
            ./cc-test-reporter after-build --exit-code $?
